# Generated by Django 4.1 on 2022-09-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('bd', models.DateField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='CBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=80)),
                ('results', models.FloatField(blank=True, null=True)),
                ('test_units', models.CharField(max_length=210)),
                ('ref', models.CharField(max_length=200, verbose_name='ref. values')),
                ('test_date', models.DateField()),
                ('patients_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=80)),
                ('results', models.FloatField(blank=True, null=True)),
                ('test_units', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=200, verbose_name='ref. values')),
                ('test_date', models.DateField()),
                ('patients_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.patient')),
            ],
        ),
    ]
