# Generated by Django 4.1 on 2022-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
