# Generated by Django 4.1 on 2022-09-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_patients_patient_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
