# Generated by Django 4.1 on 2022-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bd',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
