# Generated by Django 4.1 on 2022-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_cbc_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbc',
            name='ref',
            field=models.CharField(choices=[('(4.3 - 5.6)', '(4.3 - 5.6)'), ('(13.7 - 16.5)', '(13.7 - 16.5)'), ('(40 - 50)', '(40 - 50)')], default='', max_length=200, verbose_name='Reference values'),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='test_units',
            field=models.CharField(choices=[('10^6/µl', '10^6/µl'), ('g/dL', 'g/dL'), ('%', '%')], default='', max_length=200, verbose_name='Units'),
        ),
    ]
