# Generated by Django 4.1 on 2022-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_bch_test_name_alter_enzymes_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bch',
            name='test_name',
            field=models.CharField(choices=[('GLUCOSE', 'Glucose'), ('CREATININE', 'Creatinine'), ('URIC ACID', 'Uric acid')], default='', max_length=80, verbose_name='Test name'),
        ),
        migrations.AlterField(
            model_name='enzymes',
            name='test_name',
            field=models.CharField(choices=[('AST', 'AST'), ('ALT', 'ALT'), ('GAMMA-GT', 'Gamma-GT')], default='', max_length=80, verbose_name='Test name'),
        ),
    ]
